/*
 * Product Catalog API
 * The Product Catalog API enables customers browse Acme Pet Supplies great range of pet products and their product reviews.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: john.smith@acme-pet-supplies.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.acmepetsupplies.api;

import com.acmepetsupplies.client.ApiException;
import com.acmepetsupplies.model.Error;
import com.acmepetsupplies.model.Product;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductsApi
 */
public class ProductsApiTest {

    private final ProductsApi api = new ProductsApi();

    /**
     * View a product&#39;s details
     *
     * View a product&#39;s details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void viewProductTest() throws ApiException {
        ProductsApi api = new ProductsApi();    
        api.getApiClient().setBasePath("http://localhost:8000");    
        api.getApiClient().addDefaultHeader("Host", "api.acme-pet-supplies.com");    
        api.getApiClient().setApiKey("my_secret_api_key");    
        UUID id = UUID.randomUUID();
        Product response = api.viewProduct(id);    
        System.out.println(response);

    }

}
