/*
 * Product Catalog API
 * The Product Catalog API enables customers browse Acme Pet Supplies great range of pet products and their product reviews.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: john.smith@acme-pet-supplies.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;


import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.Product;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductsApi
 */
@Disabled
public class ProductsApiTest {


    private  ProductsApi api;

    @BeforeEach
    public void setUp(){
        api = new ProductsApi();
        api.getApiClient().setBasePath("http://localhost:8000");
        api.getApiClient().addDefaultHeader("Host", "api.acme-pet-supplies.com");
        api.getApiClient().setApiKey("my_secret_api_key");
    }

    /**
     * View a product&#39;s details
     *
     * View a product&#39;s details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void viewProductTest() throws ApiException {
        UUID id = UUID.randomUUID();
        Product response = api.viewProduct(id);
        System.out.println(response);
    }

}
